---

#- name: Debug hostvars
#  debug:
#    msg: "{{ hostvars[groups['shard_masters'][0]] }}"

- name: Copy add_shards.js script
  template: src=add_shards.js.j2 dest=/tmp/add_shards.js
  become: yes

- name: Ensure mongod is stopped to free ports
  service:
    name: mongodb
    state: stopped
  become: yes

- name: Ensure mongoc is running
  service:
    name: mongoc
    state: started
  become: yes

- pause:
    seconds: 10

- name: Add Shards to Cluster
  shell: sudo service mongos start && mongo testdb /tmp/add_shards.js
  register: add_shards_output
  retries: 10
  delay: 10
  until: add_shards_output.rc == 0
  become: yes

- name: Show debuglog of add_shards
  debug: msg="{{ add_shards_output.stdout_lines }}"

- name: Copy Test Data
  template: src=insert_random.js dest=/tmp/insert_random.js

- name: Insert Test Data
  shell: mongo testdb /tmp/insert_random.js
