---

- name: Install mongodb-package
  apt:
    name: mongodb
    state: present
  become: yes

- name: create mongodb.conf
  template: src=mongodb.conf.j2 dest=/etc/mongodb.conf
  become: yes

- name: create mongodb data directory
  file: path=/var/lib/mongodb state=directory owner=mongodb group=mongodb
  become: yes

# https://docs.mongodb.com/v2.4/tutorial/deploy-replica-set/

- name: restart mongodb
  service:
    name: mongodb
    state: restarted
  become: true

- name: initiate replication set
  shell: mongo --eval "rs.initiate()"
  when: "'replication_master' in group_names"

- name: Set replication.replSetName in Configuration
  lineinfile:
    path: /etc/mongodb.conf
    regexp: '^replSet ='
    line: 'replSet = rs1'
  become: yes

- name: restart mongodb
  service:
    name: mongodb
    state: restarted
  become: true

