- hosts: all
  roles:
  - role: setup_raspberry

- import_playbook: reset_sharding.yml

- hosts: mongo_servers
  roles:
  - role: setup_mongod

- hosts: mongos
  roles:
  - role: install_mongodb

- hosts: shard_servers
  roles:
  - role: repshards_config

- hosts: shard_masters
  roles:
  - role: setup_repshards

- hosts: mongoc
  roles:
  - role: setup_mongoc

- hosts: mongos
  roles:
  - role: init_repshards
