- hosts: all
  roles: 
  - role: setup_raspberry

- hosts: mongod_servers
  roles:
  - role: setup_mongod

- hosts: shard_masters
  roles:
  - role: init_single_rs

- hosts: mongoc
  roles:
  - role: setup_mongoc

- hosts: mongos
  roles:
  - role: setup_mongos
  - role: setup_shards
