---

- name: Install mongodb-package
  apt:
    name: mongodb
    state: present
    update_cache: yes
  become: yes

- name: create mongodb.conf
  template: src=mongodb.conf.j2 dest=/etc/mongodb.conf
  become: yes

- name: create mongodb data directory
  file: path=/var/lib/mongodb state=directory owner=mongodb group=mongodb
  become: yes

- name: restart mongodb
  service:
    name: mongodb
    state: restarted
  become: true

